/*
 * ardour4-prefs: Application Entry Point
 * Phase 0 — GTK4/Libadwaita migration of Ardour Plus
 *
 * Initialises libardour in config-only mode (audio engine object is created
 * but never started), then opens the AdwPreferencesWindow.
 *
 * ARDOUR::init() flow:
 *   - loads PBD, Temporal
 *   - creates RCConfiguration (loads ~/.config/ardour8/ardour.rc)
 *   - creates PluginManager singleton (no scan yet)
 *   - calls AudioEngine::create() — creates the object, does NOT start it
 *   No audio thread is ever started; this binary is UI-only.
 */

#include "prefs_window.h"

#include <adwaita.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>

#include <locale.h>
#include <libintl.h>
#include <stdio.h>

/* Generated by Meson */
#include "ardour4_config.h"

/* libardour */
#include "ardour/ardour.h"
#include "ardour/rc_configuration.h"
#include "ardour/audioengine.h"
#include "pbd/error.h"
#include "pbd/failed_constructor.h"

/* ── VST FX dummy stubs for non-GTK2 standalone binary ── */
#include "ardour/vst_types.h"
int  vstfx_init (void*) { return 0; }
void vstfx_exit () {}
void vstfx_destroy_editor (VSTState*) {}

/* ── Error handler: route libardour PBD errors to stderr ── */
static void
pbd_error_handler (Transmitter::Channel t, const char *msg)
{
    fprintf (stderr, "[libardour %d] %s\n", (int)t, msg ? msg : "");
}

/* ── App activation callback ─────────────────────────────── */
static void
on_activate (AdwApplication *app, gpointer /*user_data*/)
{
    GtkWidget *win = ardour_prefs_window_new (app);
    gtk_window_present (GTK_WINDOW (win));
}

/* ── Main ────────────────────────────────────────────────── */
int
main (int argc, char **argv)
{
    /* Locale + i18n */
    setlocale (LC_ALL, "");
#if ENABLE_NLS
    bindtextdomain (GETTEXT_PACKAGE, ARDOUR4_LOCALE_DIR);
    bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
    textdomain (GETTEXT_PACKAGE);
#endif

    /* Route libardour diagnostics to stderr */
    static PBD::ScopedConnection pbd_error_connection;
    PBD::error.sender().connect_same_thread (pbd_error_connection, sigc::ptr_fun (pbd_error_handler));

    /*
     * Initialise libardour in config-only mode.
     *   arg1: try_hw_optimization — safe to enable, only affects DSP math
     *   arg2: localedir           — translations
     *   arg3: with_gui = false    — suppresses any GTK2 references inside libardour
     *
     * AudioEngine::create() is called inside ARDOUR::init() but the engine
     * is never started, so no JACK/ALSA/PipeWire connection is made.
     */
    const char *localedir = ARDOUR4_LOCALE_DIR;
    if (!ARDOUR::init (false, localedir, false)) {
        fprintf (stderr, "ardour4-prefs: ARDOUR::init() failed\n");
        return 1;
    }

    /* Create and run the GTK4 / Libadwaita application */
    AdwApplication *app = adw_application_new (
        "org.ardour.Prefs",
        G_APPLICATION_DEFAULT_FLAGS);

    g_signal_connect (app, "activate", G_CALLBACK (on_activate), NULL);

    int status = g_application_run (G_APPLICATION (app), argc, argv);

    /* Clean shutdown — save any modified config */
    if (ARDOUR::Config)
        ARDOUR::Config->save_state ();

    ARDOUR::cleanup ();
    g_object_unref (app);
    return status;
}
