/*
 * ardour4-prefs: Preferences Window Implementation
 * Phase 0 — GTK4/Libadwaita migration of Ardour Plus
 *
 * Maps every rc_option_editor.cc preference page to a native
 * AdwPreferencesPage + AdwPreferencesGroup with proper Adw row types.
 *
 * Config access goes through ARDOUR::RCConfiguration and
 * UIConfiguration::instance() — the same objects the GTK2 binary uses,
 * writing to the same ~/.config/ardour8/ardour.rc file.
 */

#include "prefs_window.h"

/* Generated by Meson — defines ARDOUR4_SHARED_CSS_DIR, ARDOUR4_LOCALE_DIR, etc. */
#include "ardour4_config.h"

#include <adwaita.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>

/* ── libardour / Ardour UI config headers ─────────────────────── */
#include "ardour/ardour.h"
#include "ardour/rc_configuration.h"
/* NOTE: audioengine.h is intentionally NOT included here — the prefs window
 * only reads ARDOUR::Config and UIConfiguration; it never touches the engine.
 * audioengine.h is included by main.cc, which calls ARDOUR::init(). */
#include "ui_configuration.h"

/* ── CSS loader ─────────────────────────────────────────────── */
static void
load_css (void)
{
    GtkCssProvider *provider = gtk_css_provider_new ();

    /* Load from the shared/ directory relative to the binary location.
     * During development this is the source tree path. */
    const char *src_css = ARDOUR4_SHARED_CSS_DIR "/style.css";
    gtk_css_provider_load_from_path (provider, src_css);
    gtk_style_context_add_provider_for_display (
        gdk_display_get_default (),
        GTK_STYLE_PROVIDER (provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    g_object_unref (provider);
}

/* ══════════════════════════════════════════════════════════════
 *  Helper macros — build Adw rows quickly
 * ══════════════════════════════════════════════════════════════ */

/* Bool: maps to AdwSwitchRow */
static AdwSwitchRow *
make_switch_row (const char *title,
                 const char *subtitle,
                 gboolean    initial)
{
    AdwSwitchRow *row = ADW_SWITCH_ROW (adw_switch_row_new ());
    adw_preferences_row_set_title (ADW_PREFERENCES_ROW (row), title);
    if (subtitle && *subtitle)
        adw_action_row_set_subtitle (ADW_ACTION_ROW (row), subtitle);
    adw_switch_row_set_active (row, initial);
    return row;
}

/* Combo: maps to AdwComboRow with a string list */
static AdwComboRow *
make_combo_row (const char  *title,
                const char  *subtitle,
                const char **items,   /* NULL-terminated */
                guint        selected)
{
    GtkStringList *sl = gtk_string_list_new (items);
    AdwComboRow   *row = ADW_COMBO_ROW (adw_combo_row_new ());
    adw_preferences_row_set_title (ADW_PREFERENCES_ROW (row), title);
    if (subtitle && *subtitle)
        adw_action_row_set_subtitle (ADW_ACTION_ROW (row), subtitle);
    adw_combo_row_set_model (row, G_LIST_MODEL (sl));
    adw_combo_row_set_selected (row, selected);
    return row;
}

/* Spin: maps to AdwSpinRow */
static AdwSpinRow *
make_spin_row (const char *title,
               const char *subtitle,
               double      min,
               double      max,
               double      step,
               double      val)
{
    GtkAdjustment *adj = gtk_adjustment_new (val, min, max, step, step * 10, 0);
    AdwSpinRow    *row = ADW_SPIN_ROW (adw_spin_row_new (adj, step, 0));
    adw_preferences_row_set_title (ADW_PREFERENCES_ROW (row), title);
    if (subtitle && *subtitle)
        adw_action_row_set_subtitle (ADW_ACTION_ROW (row), subtitle);
    return row;
}

/* Entry: maps to AdwEntryRow */
static AdwEntryRow *
make_entry_row (const char *title, const char *initial_text)
{
    AdwEntryRow *row = ADW_ENTRY_ROW (adw_entry_row_new ());
    adw_preferences_row_set_title (ADW_PREFERENCES_ROW (row), title);
    if (initial_text && *initial_text)
        gtk_editable_set_text (GTK_EDITABLE (row), initial_text);
    return row;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: General
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_general (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("General"));
    adw_preferences_page_set_icon_name (page, "preferences-system-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    /* ── Group: Session Management ─── */
    AdwPreferencesGroup *g_session = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_session, _("Session Management"));
    adw_preferences_group_set_description (g_session,
        _("Control how Ardour handles sessions at startup and shutdown."));

    adw_preferences_group_add (g_session, GTK_WIDGET (make_switch_row (
        _("Auto-connect to session on startup"),
        _("Automatically connect master bus outputs when creating a new session"),
        cfg->get_auto_connect_standard_busses ())));

    adw_preferences_group_add (g_session, GTK_WIDGET (make_switch_row (
        _("Only close dialog on \"Close Session\""),
        _("Prevent accidental session close from the window close button"),
        false)));

    adw_preferences_group_add (g_session, GTK_WIDGET (make_spin_row (
        _("Maximum recent sessions"), NULL,
        0, 50, 1,
        cfg->get_max_recent_sessions ())));

    adw_preferences_page_add (page, g_session);

    /* ── Group: Editor Undo ─── */
    AdwPreferencesGroup *g_undo = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_undo, _("Editor Undo"));

    adw_preferences_group_add (g_undo, GTK_WIDGET (make_switch_row (
        _("Limit undo history"),
        _("Cap the number of undo steps kept in memory"),
        (cfg->get_history_depth () > 0))));

    adw_preferences_group_add (g_undo, GTK_WIDGET (make_spin_row (
        _("Undo history depth"), _("Number of undo steps to keep"),
        1, 500, 1,
        cfg->get_history_depth ())));

    adw_preferences_group_add (g_undo, GTK_WIDGET (make_switch_row (
        _("Save undo history with session"),
        _("Restore undo history when re-opening a session"),
        cfg->get_save_history ())));

    adw_preferences_page_add (page, g_undo);

    /* ── Group: Import ─── */
    AdwPreferencesGroup *g_import = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_import, _("Import"));

    adw_preferences_group_add (g_import, GTK_WIDGET (make_switch_row (
        _("Drag-and-drop creates regions"),
        _("When unchecked, drag-and-drop always opens the import dialog"),
        UIConfiguration::instance().get_only_copy_imported_files ())));

    adw_preferences_group_add (g_import, GTK_WIDGET (make_switch_row (
        _("Automatic analysis of audio"),
        _("Compute transients and loudness in the background after import"),
        cfg->get_auto_analyse_audio ())));

    adw_preferences_page_add (page, g_import);

    /* ── Group: Export ─── */
    AdwPreferencesGroup *g_export = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_export, _("Export"));

    adw_preferences_group_add (g_export, GTK_WIDGET (make_switch_row (
        _("Save loudness analysis with session"),
        NULL,
        UIConfiguration::instance().get_save_export_mixer_screenshot ())));

    adw_preferences_group_add (g_export, GTK_WIDGET (make_switch_row (
        _("Open export folder when done"),
        NULL,
        false)));

    adw_preferences_page_add (page, g_export);

    /* ── Group: Updates ─── */
    AdwPreferencesGroup *g_update = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_update, _("Updates"));

    adw_preferences_group_add (g_update, GTK_WIDGET (make_switch_row (
        _("Check for new Ardour versions on startup"),
        NULL,
        false)));

    adw_preferences_page_add (page, g_update);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Appearance
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_appearance (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Appearance"));
    adw_preferences_page_set_icon_name (page, "applications-graphics-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    /* ── Group: Theme ─── */
    AdwPreferencesGroup *g_theme = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_theme, _("Theme"));

    /* color_file contains the theme name; dark if it contains "dark" */
    bool is_dark = (UIConfiguration::instance().get_color_file().find("dark") != std::string::npos);
    adw_preferences_group_add (g_theme, GTK_WIDGET (make_switch_row (
        _("Use dark theme"),
        NULL,
        is_dark)));

    adw_preferences_group_add (g_theme, GTK_WIDGET (make_switch_row (
        _("Draw region name on waveform"),
        NULL,
        UIConfiguration::instance().get_show_region_names ())));

    adw_preferences_page_add (page, g_theme);

    /* ── Group: Size & Scale ─── */
    AdwPreferencesGroup *g_scale = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_scale, _("Size and Scale"));
    adw_preferences_group_set_description (g_scale,
        _("Applies immediately. Restart may be required for some elements."));

    adw_preferences_group_add (g_scale, GTK_WIDGET (make_spin_row (
        _("GUI scale factor"), _("Multiplier applied to all UI element sizes"),
        50, 400, 5,
        /* font_scale is stored in 1024ths — convert to percent */
        (double)(UIConfiguration::instance().get_font_scale()) / 10.24)));

    /* DPI override: UIConfig has no single toggle; use a placeholder for now */
    (void)cfg;  /* suppress unused warning */

    adw_preferences_page_add (page, g_scale);

    /* ── Group: Toolbar ─── */
    AdwPreferencesGroup *g_toolbar = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_toolbar, _("Main Toolbar"));

    adw_preferences_group_add (g_toolbar, GTK_WIDGET (make_switch_row (
        _("Show secondary clock"), NULL,
        UIConfiguration::instance().get_show_secondary_clock ())));

    adw_preferences_group_add (g_toolbar, GTK_WIDGET (make_switch_row (
        _("Show Selection info in toolbar"), NULL,
        UIConfiguration::instance().get_show_toolbar_selclock ())));

    adw_preferences_group_add (g_toolbar, GTK_WIDGET (make_switch_row (
        _("Show Monitor Section info in toolbar"), NULL,
        UIConfiguration::instance().get_show_toolbar_monitor_info ())));

    adw_preferences_group_add (g_toolbar, GTK_WIDGET (make_switch_row (
        _("Super-rapid clock update"),
        _("Refresh transport clocks at the highest available rate"),
        UIConfiguration::instance().get_super_rapid_clock_update ())));

    adw_preferences_page_add (page, g_toolbar);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Editor
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_editor (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Editor"));
    adw_preferences_page_set_icon_name (page, "text-editor-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    /* ── Group: Behavior ─── */
    AdwPreferencesGroup *g_behavior = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_behavior, _("Behavior"));

    adw_preferences_group_add (g_behavior, GTK_WIDGET (make_switch_row (
        _("Snap to grid by default"),
        NULL,
        true)));

    adw_preferences_group_add (g_behavior, GTK_WIDGET (make_switch_row (
        _("Region boundaries are snap targets"),
        NULL,
        true)));

    adw_preferences_group_add (g_behavior, GTK_WIDGET (make_switch_row (
        _("Auto-scroll timeline during playback"),
        _("Keep the playhead visible while the transport is rolling"),
        UIConfiguration::instance().get_autoscroll_editor ())));

    adw_preferences_group_add (g_behavior, GTK_WIDGET (make_switch_row (
        _("Follow playhead when not recording"),
        NULL,
        UIConfiguration::instance().get_follow_edits ())));

    adw_preferences_page_add (page, g_behavior);

    /* ── Group: Waveforms ─── */
    AdwPreferencesGroup *g_wave = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_wave, _("Waveforms"));

    adw_preferences_group_add (g_wave, GTK_WIDGET (make_switch_row (
        _("Show waveforms"),
        NULL,
        UIConfiguration::instance().get_show_waveforms ())));

    adw_preferences_group_add (g_wave, GTK_WIDGET (make_switch_row (
        _("Show waveforms while recording"),
        _("Real-time waveform display while capturing audio"),
        UIConfiguration::instance().get_show_waveforms_while_recording ())));

    const char *wave_styles[] = { _("Traditional"), _("Rectified"), NULL };
    adw_preferences_group_add (g_wave, GTK_WIDGET (make_combo_row (
        _("Waveform style"), NULL,
        wave_styles,
        (guint)UIConfiguration::instance().get_waveform_shape ())));

    adw_preferences_page_add (page, g_wave);

    /* ── Group: Zoom ─── */
    AdwPreferencesGroup *g_zoom = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_zoom, _("Scroll and Zoom"));

    adw_preferences_group_add (g_zoom, GTK_WIDGET (make_switch_row (
        _("Zoom focus follows mouse"),
        _("Zoom centers on the mouse pointer position"),
        UIConfiguration::instance().get_use_mouse_position_as_zoom_focus_on_scroll ())));

    adw_preferences_page_add (page, g_zoom);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Mixer
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_mixer (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Mixer"));
    adw_preferences_page_set_icon_name (page, "multimedia-equalizer-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    AdwPreferencesGroup *g_strip = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_strip, _("Mixer Strip"));

    adw_preferences_group_add (g_strip, GTK_WIDGET (make_switch_row (
        _("Show record-enable buttons in Mixer"),
        NULL,
        UIConfiguration::instance().get_mixer_strip_rec_enable ())));

    adw_preferences_group_add (g_strip, GTK_WIDGET (make_switch_row (
        _("Show inline plugin displays"),
        _("Render plugin GUIs directly in the processor box"),
        true)));

    adw_preferences_group_add (g_strip, GTK_WIDGET (make_switch_row (
        _("Save mixer screenshot on export"),
        NULL,
        UIConfiguration::instance().get_save_export_mixer_screenshot ())));

    adw_preferences_page_add (page, g_strip);

    AdwPreferencesGroup *g_meter = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_meter, _("Metering"));

    const char *meter_types[] = {
        _("Peak"), _("RMS + Peak"), _("K-12 RMS"), _("K-14 RMS"),
        _("K-20 RMS"), _("VU"), _("IEC 1: DIN"), _("IEC 2: BBC"),
        _("IEC 2: EBU"), NULL
    };
    adw_preferences_group_add (g_meter, GTK_WIDGET (make_combo_row (
        _("Default meter type"), NULL,
        meter_types, 0)));

    adw_preferences_page_add (page, g_meter);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Transport
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_transport (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Transport"));
    adw_preferences_page_set_icon_name (page, "media-playback-start-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    AdwPreferencesGroup *g_transport = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_transport, _("Playback"));

    adw_preferences_group_add (g_transport, GTK_WIDGET (make_switch_row (
        _("Stop playback at session end"),
        NULL,
        cfg->get_stop_at_session_end ())));

    adw_preferences_group_add (g_transport, GTK_WIDGET (make_switch_row (
        _("Preroll before record"),
        _("Play back a short lead-in before starting to record"),
        cfg->get_preroll_seconds () > 0)));

    adw_preferences_group_add (g_transport, GTK_WIDGET (make_spin_row (
        _("Preroll seconds"), NULL,
        0, 30, 0.5,
        cfg->get_preroll_seconds ())));

    adw_preferences_group_add (g_transport, GTK_WIDGET (make_switch_row (
        _("Punch in/out follows transport"),
        NULL,
        false)));

    adw_preferences_group_add (g_transport, GTK_WIDGET (make_switch_row (
        _("Looping enabled by default"),
        NULL,
        cfg->get_loop_is_mode ())));

    adw_preferences_page_add (page, g_transport);

    AdwPreferencesGroup *g_click = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_click, _("Metronome / Click"));

    adw_preferences_group_add (g_click, GTK_WIDGET (make_switch_row (
        _("Use built-in click"),
        NULL,
        cfg->get_click_sound ().empty ())));

    adw_preferences_group_add (g_click, GTK_WIDGET (make_switch_row (
        _("Emphasize downbeat"),
        NULL,
        cfg->get_use_click_emphasis ())));

    adw_preferences_group_add (g_click, GTK_WIDGET (make_spin_row (
        _("Click volume"), _("Level in dB (0 = unity)"),
        -60, 6, 1,
        cfg->get_click_gain ())));

    adw_preferences_page_add (page, g_click);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: MIDI
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_midi (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("MIDI"));
    adw_preferences_page_set_icon_name (page, "network-wireless-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    AdwPreferencesGroup *g_midi = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_midi, _("MIDI Editing"));

    adw_preferences_group_add (g_midi, GTK_WIDGET (make_switch_row (
        _("Sound MIDI notes while editing"),
        _("Audition notes when moved or drawn in the piano roll"),
        UIConfiguration::instance().get_sound_midi_notes ())));

    adw_preferences_group_add (g_midi, GTK_WIDGET (make_switch_row (
        _("Allow non-quarter-note MIDI meter"),
        NULL,
        UIConfiguration::instance().get_allow_non_quarter_pulse ())));

    adw_preferences_group_add (g_midi, GTK_WIDGET (make_switch_row (
        _("Send MTC"),
        _("Transmit MIDI Time Code to external devices"),
        cfg->get_send_mtc ())));

    adw_preferences_group_add (g_midi, GTK_WIDGET (make_switch_row (
        _("Send MMC"),
        _("Transmit MIDI Machine Control messages"),
        cfg->get_send_mmc ())));

    adw_preferences_group_add (g_midi, GTK_WIDGET (make_switch_row (
        _("Send MIDI Clock"),
        NULL,
        cfg->get_send_midi_clock ())));

    adw_preferences_page_add (page, g_midi);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Plugins
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_plugins (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Plugins"));
    adw_preferences_page_set_icon_name (page, "application-x-addon-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    AdwPreferencesGroup *g_scan = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_scan, _("Plugin Scanning"));

    adw_preferences_group_add (g_scan, GTK_WIDGET (make_switch_row (
        _("Scan for plugins on startup"),
        _("Automatically discover new or changed plugins when Ardour starts"),
        cfg->get_discover_plugins_on_start ())));

    adw_preferences_group_add (g_scan, GTK_WIDGET (make_spin_row (
        _("Plugin scan timeout"), _("Seconds before a hung plugin is abandoned"),
        1, 300, 1,
        cfg->get_plugin_scan_timeout () / 10)));   /* stored in deciseconds */

    adw_preferences_group_add (g_scan, GTK_WIDGET (make_switch_row (
        _("Use VST 2 plugins"),
        NULL,
        cfg->get_use_lxvst ())));

    adw_preferences_group_add (g_scan, GTK_WIDGET (make_switch_row (
        _("Use VST 3 plugins"),
        NULL,
        cfg->get_use_vst3 ())));

    adw_preferences_page_add (page, g_scan);

    AdwPreferencesGroup *g_gui = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_gui, _("Plugin GUI"));

    adw_preferences_group_add (g_gui, GTK_WIDGET (make_switch_row (
        _("Automatically open plugin GUIs"),
        _("Show native plugin GUI when a plugin is added"),
        cfg->get_use_plugin_own_gui ())));

    adw_preferences_group_add (g_gui, GTK_WIDGET (make_switch_row (
        _("Prefer native plugin GUIs"),
        _("Use vendor GUI over Ardour's generic controls when available"),
        UIConfiguration::instance().get_prefer_inline_over_gui ())));

    adw_preferences_page_add (page, g_gui);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Control Surfaces
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_surfaces (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Control Surfaces"));
    adw_preferences_page_set_icon_name (page, "input-gaming-symbolic");

    AdwPreferencesGroup *g = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g, _("Available Surfaces"));
    adw_preferences_group_set_description (g,
        _("Enable or disable hardware control surface support. "
          "Surface-specific options appear when a surface is enabled."));

    /* Enumerate discovered protocols from ControlProtocolManager */
    /* NOTE: Full implementation will iterate ControlProtocolManager::instance().control_protocol_info
     * For Phase 0 we show representative surfaces as placeholders */
    const char *surfaces[] = {
        "Mackie Control Universal", "Open Sound Control (OSC)",
        "PreSonus FaderPort", "Generic MIDI", NULL
    };
    for (int i = 0; surfaces[i]; ++i) {
        AdwSwitchRow *row = ADW_SWITCH_ROW (adw_switch_row_new ());
        adw_preferences_row_set_title (ADW_PREFERENCES_ROW (row), surfaces[i]);
        adw_switch_row_set_active (row, FALSE);
        adw_preferences_group_add (g, GTK_WIDGET (row));
    }

    adw_preferences_page_add (page, g);
    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Video
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_video (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Video"));
    adw_preferences_page_set_icon_name (page, "video-display-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    AdwPreferencesGroup *g = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g, _("Video Server"));

    adw_preferences_group_add (g, GTK_WIDGET (make_entry_row (
        _("Video server URL"),
        cfg->get_video_server_url ().c_str ())));

    adw_preferences_group_add (g, GTK_WIDGET (make_switch_row (
        _("Include video in export"),
        NULL,
        cfg->get_video_advanced_setup ())));

    adw_preferences_page_add (page, g);
    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  PAGE: Performance
 * ══════════════════════════════════════════════════════════════ */
AdwPreferencesPage *
ardour_prefs_page_performance (void)
{
    AdwPreferencesPage *page = ADW_PREFERENCES_PAGE (adw_preferences_page_new ());
    adw_preferences_page_set_title (page, _("Performance"));
    adw_preferences_page_set_icon_name (page, "utilities-system-monitor-symbolic");

    ARDOUR::RCConfiguration *cfg = ARDOUR::Config;

    AdwPreferencesGroup *g_disk = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_disk, _("Disk I/O Buffering"));

    adw_preferences_group_add (g_disk, GTK_WIDGET (make_spin_row (
        _("Playback buffer size"), _("Seconds of audio to buffer from disk"),
        1, 120, 1,
        cfg->get_audio_playback_buffer_seconds ())));

    adw_preferences_group_add (g_disk, GTK_WIDGET (make_spin_row (
        _("Record buffer size"), _("Seconds of audio to buffer before writing to disk"),
        1, 120, 1,
        cfg->get_audio_capture_buffer_seconds ())));

    adw_preferences_page_add (page, g_disk);

    AdwPreferencesGroup *g_cpu = ADW_PREFERENCES_GROUP (adw_preferences_group_new ());
    adw_preferences_group_set_title (g_cpu, _("CPU"));

    adw_preferences_group_add (g_cpu, GTK_WIDGET (make_switch_row (
        _("Denormal handling"),
        _("Flush floating-point denormals to zero (reduces CPU spikes)"),
        cfg->get_denormal_protection ())));

    adw_preferences_group_add (g_cpu, GTK_WIDGET (make_switch_row (
        _("Use hardware optimisation"),
        _("Use SSE/AVX when available for DSP operations"),
        TRUE   /* set by try_hw_optimization at init time */)));

    adw_preferences_page_add (page, g_cpu);

    return page;
}


/* ══════════════════════════════════════════════════════════════
 *  Main window assembly
 * ══════════════════════════════════════════════════════════════ */
GtkWidget *
ardour_prefs_window_new (AdwApplication *app)
{
    load_css ();

    AdwPreferencesWindow *win = ADW_PREFERENCES_WINDOW (adw_preferences_window_new ());
    gtk_window_set_application (GTK_WINDOW (win), GTK_APPLICATION (app));
    gtk_window_set_title (GTK_WINDOW (win), _("Ardour Preferences"));
    gtk_window_set_default_size (GTK_WINDOW (win), 900, 680);

    /* Search is built into AdwPreferencesWindow — no extra work needed */
    adw_preferences_window_set_search_enabled (win, TRUE);

    /* Add every page */
    adw_preferences_window_add (win, ardour_prefs_page_general ());
    adw_preferences_window_add (win, ardour_prefs_page_appearance ());
    adw_preferences_window_add (win, ardour_prefs_page_editor ());
    adw_preferences_window_add (win, ardour_prefs_page_mixer ());
    adw_preferences_window_add (win, ardour_prefs_page_transport ());
    adw_preferences_window_add (win, ardour_prefs_page_midi ());
    adw_preferences_window_add (win, ardour_prefs_page_plugins ());
    adw_preferences_window_add (win, ardour_prefs_page_surfaces ());
    adw_preferences_window_add (win, ardour_prefs_page_video ());
    adw_preferences_window_add (win, ardour_prefs_page_performance ());

    return GTK_WIDGET (win);
}
