/*
 * ardour4-shell: Application Entry Point
 * Phase 2 — GTK4/Libadwaita migration of Ardour Plus
 */

#include "shell_window.h"

#include <adwaita.h>
#include <glib/gi18n.h>
#include <gtk/gtk.h>

#include <locale.h>
#include <libintl.h>
#include <stdio.h>

/* Generated by Meson */
#include "ardour4_config.h"

/* libardour */
#include "ardour/ardour.h"
#include "ardour/rc_configuration.h"
#include "ardour/audioengine.h"
#include "pbd/error.h"
#include "pbd/failed_constructor.h"

/* VST FX dummy stubs for non-GTK2 standalone binary */
#include "ardour/vst_types.h"
int  vstfx_init (void*) { return 0; }
void vstfx_exit () {}
void vstfx_destroy_editor (VSTState*) {}

/* ── Error handler ── */
static void
pbd_error_handler (Transmitter::Channel t, const char *msg)
{
    fprintf (stderr, "[libardour %d] %s\n", (int)t, msg ? msg : "");
}

/* ── App activation callback ─────────────────────────────── */
static void
on_activate (AdwApplication *app, gpointer /*user_data*/)
{
    GtkWidget *win = ardour_shell_window_new (GTK_APPLICATION (app));
    gtk_window_present (GTK_WINDOW (win));
}

/* ── Main ────────────────────────────────────────────────── */
int
main (int argc, char **argv)
{
    /* Locale + i18n */
    setlocale (LC_ALL, "");
#if ENABLE_NLS
    bindtextdomain (GETTEXT_PACKAGE, ARDOUR4_LOCALE_DIR);
    bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
    textdomain (GETTEXT_PACKAGE);
#endif

    /* Route libardour diagnostics to stderr */
    static PBD::ScopedConnection pbd_error_connection;
    PBD::error.sender().connect_same_thread (pbd_error_connection, sigc::ptr_fun (pbd_error_handler));

    /* Initialise libardour in config-only mode */
    const char *localedir = ARDOUR4_LOCALE_DIR;
    if (!ARDOUR::init (false, localedir, false)) {
        fprintf (stderr, "ardour4-shell: ARDOUR::init() failed\n");
        return 1;
    }

    /* Create and run the GTK4 / Libadwaita application */
    AdwApplication *app = adw_application_new (
        "org.ardour.Shell",
        G_APPLICATION_DEFAULT_FLAGS);

    g_signal_connect (app, "activate", G_CALLBACK (on_activate), NULL);

    int status = g_application_run (G_APPLICATION (app), argc, argv);

    if (ARDOUR::Config)
        ARDOUR::Config->save_state ();

    ARDOUR::cleanup ();
    g_object_unref (app);
    return status;
}
