/*
 * ardour4-qt: Main Entry Point — Qt6 Port
 * Phase Qt6-A
 */

#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QIcon>
#include <QPalette>
#include <QDir>
#include <QUrl>
#include <stdio.h>

#pragma push_macro("emit")
#pragma push_macro("slots")
#pragma push_macro("signals")
#undef emit
#undef slots
#undef signals

#include "ardour/ardour.h"
#include "ardour/audioengine.h"
#include "ardour/rc_configuration.h"
#include "ardour/vst_types.h"
#include "pbd/error.h"
#include "pbd/transmitter.h"


#pragma pop_macro("signals")
#pragma pop_macro("slots")
#pragma pop_macro("emit")


#include <QProcess>
#include "transport_bar.h"
#include "editor_workspace.h"
#include "session_bridge.h"
#include "theme.h"

int  vstfx_init(void*) { return 0; }
void vstfx_exit() {}
void vstfx_destroy_editor(VSTState*) {}

static void pbd_error_handler(Transmitter::Channel t, const char *msg)
{
    fprintf(stderr, "[libardour %d] %s\n", (int)t, msg ? msg : "");
}


int main(int argc, char *argv[])
{
    /* Route libardour diagnostics to stderr */
    static PBD::ScopedConnection pbd_error_connection;
    PBD::error.sender().connect_same_thread(pbd_error_connection, sigc::ptr_fun(pbd_error_handler));

    /* Initialise libardour engine */
    if (!ARDOUR::init(false, "/usr/share/locale", false)) {
        fprintf(stderr, "ardour4-qt: ARDOUR::init() failed\n");
    }

    // Launch GTK4 + Libadwaita startup and splash screen flow (ardour4-dialogs) if available
    const char *qpa = getenv("QT_QPA_PLATFORM");
    bool isOffscreen = (qpa && strcmp(qpa, "offscreen") == 0);
    if (!isOffscreen) {
        const char *topEnv = getenv("TOP");
        QString topDir = topEnv ? QString::fromLocal8Bit(topEnv) : QDir::currentPath();
        QString gtk4Dialogs = topDir + "/built_binaries/ardour4-dialogs#build15";
        if (!QFile::exists(gtk4Dialogs)) {
            gtk4Dialogs = topDir + "/gtk4_ardour/builddir/adw_dialogs/ardour4-dialogs";
        }
        if (QFile::exists(gtk4Dialogs)) {
            printf("[Ardour Plus Qt6] Presenting GTK4 + Libadwaita Session & Engine Setup Dialog...\n");
            fflush(stdout);
            QProcess::execute(gtk4Dialogs, QStringList());
        }
    }

    QGuiApplication app(argc, argv);
    app.setApplicationName("Ardour Plus Qt6");
    app.setOrganizationName("ArdourProject");

    // Force Ardour dark color palette on QGuiApplication
    QPalette palette = app.palette();
    palette.setColor(QPalette::Window, QColor("#1e1e1e"));
    palette.setColor(QPalette::WindowText, QColor("#f1f3f5"));
    palette.setColor(QPalette::Base, QColor("#1e1e1e"));
    palette.setColor(QPalette::AlternateBase, QColor("#242424"));
    palette.setColor(QPalette::ToolTipBase, QColor("#313131"));
    palette.setColor(QPalette::ToolTipText, QColor("#f1f3f5"));
    palette.setColor(QPalette::Text, QColor("#f1f3f5"));
    palette.setColor(QPalette::Button, QColor("#393939"));
    palette.setColor(QPalette::ButtonText, QColor("#f1f3f5"));
    palette.setColor(QPalette::BrightText, QColor("#ffffff"));
    palette.setColor(QPalette::Highlight, QColor("#3584e4"));
    palette.setColor(QPalette::HighlightedText, QColor("#ffffff"));
    app.setPalette(palette);

    // Register custom C++ types to QML
    qmlRegisterType<TransportBar>("Ardour.Core", 1, 0, "TransportBar");
    qmlRegisterType<TrackListModel>("Ardour.Core", 1, 0, "TrackListModel");
    qmlRegisterType<SessionBridge>("Ardour.Core", 1, 0, "SessionBridge");

    QQmlApplicationEngine engine;

    // Instantiate global C++ models and inject into QML context
    ArdourTheme ardourTheme;
    TransportBar transportBar;
    TrackListModel trackListModel;
    SessionBridge sessionBridge;

    engine.rootContext()->setContextProperty("Theme", &ardourTheme);
    engine.rootContext()->setContextProperty("globalTransport", &transportBar);
    engine.rootContext()->setContextProperty("globalTrackModel", &trackListModel);
    engine.rootContext()->setContextProperty("globalSession", &sessionBridge);

    // QML import paths
    engine.addImportPath("qrc:/");

    // Primary resource path generated by qt_add_qml_module
    QUrl url(QStringLiteral("qrc:/qt/qml/ardour4qt/qml_shell/qml/MainShell.qml"));
    
    // Fallback to local file if resource load fails during dev
    QDir devDir(QCoreApplication::applicationDirPath() + "/../qml_shell/qml");
    if (devDir.exists("MainShell.qml") && !QFile::exists(":/qt/qml/ardour4qt/qml_shell/qml/MainShell.qml")) {
        url = QUrl::fromLocalFile(devDir.absoluteFilePath("MainShell.qml"));
    }

    QObject::connect(
        &engine,
        &QQmlApplicationEngine::objectCreated,
        &app,
        [url](QObject *obj, const QUrl &objUrl) {
            if (!obj && url == objUrl)
                QCoreApplication::exit(-1);
        },
        Qt::QueuedConnection
    );

    engine.load(url);

    int status = app.exec();

    if (ARDOUR::Config) {
        ARDOUR::Config->save_state();
    }
    ARDOUR::cleanup();

    return status;
}

